language: php

php:
  - 7.3
  - 7.4
  - hhvm

before_script:
  - travis_retry composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

script: vendor/bin/phpunit --verbose

notifications:
  email:
    on_success: never
