name: Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4]
        laravel: [11.*, 12.*]
        dependency-version: [prefer-stable]
        include:
          - php: 8.3
            laravel: 11.*
            dependency-version: prefer-stable
            testbench: ^9.0
          - php: 8.4
            laravel: 11.*
            dependency-version: prefer-stable
            testbench: ^9.0
          - php: 8.3
            laravel: 12.*
            dependency-version: prefer-stable
            testbench: ^10.0
          - php: 8.4
            laravel: 12.*
            dependency-version: prefer-stable
            testbench: ^10.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, sqlite3, xdebug
        coverage: xdebug

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

    - name: Copy phpunit.xml.dist
      run: cp phpunit.xml.dist phpunit.xml

    - name: Execute tests (Unit and Feature) via PHPUnit
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true

  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4]
        laravel: [11.*, 12.*]
        dependency-version: [prefer-stable]
        include:
          - php: 8.3
            laravel: 11.*
            dependency-version: prefer-stable
            testbench: ^9.0
          - php: 8.4
            laravel: 11.*
            dependency-version: prefer-stable
            testbench: ^9.0
          - php: 8.3
            laravel: 12.*
            dependency-version: prefer-stable
            testbench: ^10.0
          - php: 8.4
            laravel: 12.*
            dependency-version: prefer-stable
            testbench: ^10.0

    name: Static Analysis - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, sqlite3
        coverage: none

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

    - name: Run PHP CS Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Run Larastan
      run: vendor/bin/phpstan analyse



  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.3, 8.4]

    name: Lint - PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, sqlite3
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Run PHP Lint
      run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

  test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.4]
        laravel: [12.*]
        dependency-version: [prefer-stable]
        testbench: [^10.0]

    name: Coverage - PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, sqlite3, xdebug
        coverage: xdebug

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

    - name: Execute tests with coverage
      run: vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-html=coverage-html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: coverage
        name: codecov-coverage
        fail_ci_if_error: false
        verbose: true

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-html/
        retention-days: 30 